import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        error: "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "status-danger": "#DC2626",
        "on-primary": "#ffffff",
        "on-background": "#0b1c30",
        "border-subtle": "var(--border-subtle)",
        "inverse-surface": "#213145",
        "surface-canvas": "var(--surface-canvas)",
        "inverse-on-surface": "#eaf1ff",
        "status-success-border": "#A7F3D0",
        secondary: "#565e74",
        "tertiary-fixed": "#89f5e7",
        "on-surface": "#0b1c30",
        "border-strong": "var(--border-strong)",
        surface: "#f8f9ff",
        "on-secondary-container": "#5c647a",
        "on-surface-variant": "#5a4138",
        "surface-container": "#e5eeff",
        "status-danger-border": "#FECACA",
        "primary-fixed": "#ffdbce",
        "surface-tint": "#a73a00",
        "status-info-bg": "var(--status-info-bg)",
        "on-secondary-fixed": "#131b2e",
        "tertiary-container": "#008378",
        "surface-variant": "#d3e4fe",
        "status-warning-border": "#FDE68A",
        "status-danger-bg": "var(--status-danger-bg)",
        "surface-container-highest": "#d3e4fe",
        "on-tertiary-fixed": "#00201d",
        "on-primary-container": "#fffbff",
        "surface-container-low": "#eff4ff",
        "status-success-bg": "var(--status-success-bg)",
        outline: "#8e7166",
        "on-tertiary": "#ffffff",
        "text-muted": "var(--text-muted)",
        "secondary-container": "#dae2fd",
        "on-secondary-fixed-variant": "#3f465c",
        "on-error": "#ffffff",
        "status-info-border": "#BFDBFE",
        "on-secondary": "#ffffff",
        "surface-bright": "#f8f9ff",
        "text-primary": "var(--text-primary)",
        tertiary: "#00685f",
        "outline-variant": "#e2bfb2",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#bec6e0",
        "on-error-container": "#93000a",
        "surface-dim": "var(--surface-dim)",
        "inverse-primary": "#ffb599",
        background: "var(--background)",
        "primary-container": "#cc4900",
        "status-warning-bg": "var(--status-warning-bg)",
        "surface-subtle": "var(--surface-subtle)",
        "tertiary-fixed-dim": "#6bd8cb",
        "status-warning": "#D97706",
        primary: "#a33900",
        "primary-fixed-dim": "#ffb599",
        "surface-card": "var(--surface-card)",
        "on-primary-fixed": "#370e00",
        "on-tertiary-fixed-variant": "#005049",
        "on-tertiary-container": "#f4fffc",
        "on-primary-fixed-variant": "#7f2b00",
        "secondary-fixed": "#dae2fd",
        "status-info": "#2563EB",
        "text-secondary": "var(--text-secondary)",
        "status-success": "#059669",
        "surface-container-high": "#dce9ff",
        "brand-primary": "#EA580C",
        "brand-primary-hover": "#C2410C",
        "brand-primary-subtle": "#FFF7ED",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "card-padding-spacious": "1.5rem",
        "sidebar-width": "16rem",
        "container-padding-desktop": "2rem",
        "card-padding-compact": "1rem",
        "table-row-height": "3.25rem",
        "grid-gutter": "1.25rem",
        "table-header-height": "2.5rem",
        "card-padding-standard": "1.25rem",
        "header-height": "4rem",
        "container-padding-mobile": "1rem",
        "sidebar-collapsed-width": "4.5rem",
      },
      fontFamily: {
        "table-cell": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "metric-value": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "table-cell": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg-mobile": ["26px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "700" }],
        "metric-value": ["28px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
export default config;
