"use client";

import { useEffect, useMemo, useState, type ReactNode } from "react";
import { FieldForceSelect } from "@/components/field-force-select";
import { LABEL, SELECT, MONTH_NAMES, THIS_YEAR, ReportModal, ScreenTitle, ym, link } from "@/components/mis-analysis-panels";
import { BackButton, CARD, Err, Note, NOW_M, SELECT_FF, YEARS } from "@/components/r45-panels";
import { apiClient, type Employee, type JoinLeftResult, type ResignedUsersResult, type TpDeviationResult } from "@/lib/api-client";

// Round 46 -- legacy-parity dump downloads and result screens:
//   Dump II > RCPA, Product Exposure Analysis [SKU wise detailing secs];
//   Dump > Visit - Drs, Secondary Sale, Listeddr, Chemist, Transit Bills,
//   Listed Stockist; Options > Resigned User Status, Join/Left Details;
//   TP - Deviation For Baselevel. Shared FieldForceSelect / ReportModal; the
//   downloads are real files generated by the backend (see r46-reports.ts).

const DIVISION_NAME = "Zivira Labs Pvt Ltd";
const WORKSPACE = "/admin/workspace/division-dashboard/division-navigation-tabs";
const MANAGER_ROLES = new Set(["ABM", "RBM", "ZBM", "BH", "NBH"]);
const BTN_GREY = "h-8 px-4 rounded border border-gray-400 bg-gray-100 text-sm font-semibold text-gray-800 disabled:opacity-50";
const BTN_BLUE = "h-9 px-6 rounded border border-slate-500 bg-slate-100 text-sm font-semibold text-slate-800 disabled:opacity-50";
const DL_LINK = "text-blue-700 underline font-bold cursor-pointer disabled:opacity-50 disabled:no-underline text-left";
const ADMIN_OPT = [{ value: "admin", label: "admin - Admin -" }];

function useManagers(): Employee[] {
  const [rows, setRows] = useState<Employee[]>([]);
  useEffect(() => {
    let alive = true;
    apiClient.employees().then((r) => { if (alive) setRows(r.data.filter((e) => MANAGER_ROLES.has(e.role) && e.status === "ACTIVE")); }).catch(() => { if (alive) setRows([]); });
    return () => { alive = false; };
  }, []);
  return rows;
}
function useMonthYear() { const [v, set] = useState({ m: NOW_M, y: THIS_YEAR }); return { m: v.m, y: v.y, key: ym(v.y, v.m), setM: (m: number) => set((p) => ({ ...p, m })), setY: (y: number) => set((p) => ({ ...p, y })) }; }
function MonthSel({ label, value, onChange }: { label: string; value: number; onChange: (m: number) => void }) {
  return <div className="flex flex-col gap-1"><span className={LABEL}>{label}</span><select className={SELECT} value={value} onChange={(e) => onChange(parseInt(e.target.value, 10))}>{MONTH_NAMES.map((m, i) => <option key={m} value={i + 1}>{m.slice(0, 3)}</option>)}</select></div>;
}
function YearSel({ label, value, onChange }: { label: string; value: number; onChange: (y: number) => void }) {
  return <div className="flex flex-col gap-1"><span className={LABEL}>{label}</span><select className={SELECT} value={value} onChange={(e) => onChange(parseInt(e.target.value, 10))}>{YEARS.map((y) => <option key={y} value={y}>{y}</option>)}</select></div>;
}
function TitleBar({ children, back = false }: { children: ReactNode; back?: boolean }) {
  return <div className="flex items-start justify-between"><ScreenTitle>{children}</ScreenTitle>{back && <BackButton />}</div>;
}
function useDownload() {
  const [busy, setBusy] = useState("");
  const [error, setError] = useState("");
  async function run(tag: string, path: string, query: Record<string, string>, fileName: string) {
    setBusy(tag); setError("");
    try { await apiClient.downloadMisFile(path, query, fileName); }
    catch (e) { setError(e instanceof Error ? e.message : "Download failed"); }
    finally { setBusy(""); }
  }
  return { busy, error, run };
}

// ═══ 1. Dump II > RCPA ═══════════════════════════════════════════════════
export function RcpaDumpReport() {
  const managers = useManagers();
  const [code, setCode] = useState("");
  const my = useMonthYear();
  const dl = useDownload();
  const go = (format: "xls" | "csv") => dl.run(format, "/company/mis/rcpa-dump", { employeeCode: code, month: my.key, format }, `RCPA_Dump_${my.key}.${format}`);
  return (
    <div className="space-y-5">
      <div className={CARD}>
        <TitleBar back>All Managers - RCPA</TitleBar>
        <div className="flex flex-wrap items-end gap-4">
          <FieldForceSelect value={code} onChange={setCode} employees={managers} label="Filed Force Name" />
          <MonthSel label="Month" value={my.m} onChange={my.setM} />
          <YearSel label="Year" value={my.y} onChange={my.setY} />
        </div>
        <div className="flex gap-3">
          <button type="button" className={BTN_GREY} disabled={!code || !!dl.busy} onClick={() => void go("xls")}>{dl.busy === "xls" ? "Preparing..." : "Download Excel"}</button>
          <button type="button" className={BTN_GREY} disabled={!code || !!dl.busy} onClick={() => void go("csv")}>{dl.busy === "csv" ? "Preparing..." : "Download CSV"}</button>
        </div>
        <Err msg={dl.error} />
        <Note>One row per RCPA entry of the manager&apos;s team in the month (25 columns). The CSV uses the legacy call-report convention: values unquoted, commas inside a value shown as semicolons, a trailing comma and CRLF on every line.</Note>
      </div>
    </div>
  );
}

// ═══ 2. Dump II > Product Exposure Analysis [SKU wise detailing secs] ═════
export function SkuDumpReport() {
  const my = useMonthYear();
  const dl = useDownload();
  return (
    <div className="space-y-5">
      <div className="flex justify-end max-w-5xl"><BackButton /></div>
      <div className={CARD}>
        <ScreenTitle>Product Exposure Analysis [SKU Wise Detailing Secs]</ScreenTitle>
        <div className="flex flex-wrap items-end gap-4">
          <FieldForceSelect value="admin" onChange={() => {}} employees={[]} extraOptions={ADMIN_OPT} label="Filed Force Name" disabled />
          <MonthSel label="From Month" value={my.m} onChange={my.setM} />
          <YearSel label="From Year" value={my.y} onChange={my.setY} />
        </div>
        <button type="button" className={DL_LINK} disabled={!!dl.busy} onClick={() => void dl.run("x", "/company/mis/sku-dump", { employeeCode: "admin", month: my.key }, `SKU_Wise_Detailing_${my.key}.xls`)}>{dl.busy ? "Preparing..." : "Download Excel"}</button>
        <Err msg={dl.error} />
        <Note>Tab-separated text (.xls) with one row per slide view of the company in the month: doctor or chemist, brand, product, slide name, duration in seconds, start and end time.</Note>
      </div>
    </div>
  );
}

// ═══ shared shape of the manager + month dump screens ═════════════════════
function ManagerMonthDump({ title, back, path, fileName, note, noMonth }: { title: string; back?: boolean; path: string; fileName: (key: string) => string; note: string; noMonth?: boolean }) {
  const managers = useManagers();
  const [code, setCode] = useState("");
  const my = useMonthYear();
  const dl = useDownload();
  return (
    <div className="space-y-5">
      <div className={CARD}>
        <TitleBar back={back}>{title}</TitleBar>
        <div className="flex flex-wrap items-end gap-4">
          <FieldForceSelect value={code} onChange={setCode} employees={managers} label="Filed Force Name" />
          {!noMonth && <MonthSel label="From Month" value={my.m} onChange={my.setM} />}
          {!noMonth && <YearSel label="From Year" value={my.y} onChange={my.setY} />}
        </div>
        <button type="button" className={DL_LINK} disabled={!code || !!dl.busy} onClick={() => void dl.run("x", path, { employeeCode: code, month: my.key }, fileName(my.key))}>{dl.busy ? "Preparing..." : "Download Excel"}</button>
        <Err msg={dl.error} />
        <Note>{note}</Note>
      </div>
    </div>
  );
}

// ═══ 3. Dump > Visit - Drs ════════════════════════════════════════════════
export function VisitDrsDumpReport() {
  return <ManagerMonthDump title="All Managers - Listeddr Visit" path="/company/mis/visit-drs-dump" fileName={(k) => `Listeddr_Visit_${k}.xlsx`} note="Sheet tab1: one row per listed doctor of the manager's team with visit count and dates (dd/mm/yyyy) for MR, BH, RBM, ABM, ZBM, BRM, NBM, Sr ABM, MH and SM, counting each designation's own calls and joint-work visits." />;
}
// ═══ 4. Dump > Secondary Sale ═════════════════════════════════════════════
export function SsDumpReport() {
  return <ManagerMonthDump title="SS Dump" path="/company/mis/ss-dump" fileName={(k) => `SS_Dump_${k}.xlsx`} note="Sheet SS from the Secondary Sales master (Masters > Sales > Secondary Sales). Rows are matched to the field force by Field Force Name, or by HQ when no name is entered. No legacy sample was available, so the column layout is inferred." />;
}

// ═══ 5. Dump > Listeddr ═══════════════════════════════════════════════════
export function ListeddrDumpReport() {
  const managers = useManagers();
  const [code, setCode] = useState("");
  const dl = useDownload();
  useEffect(() => { if (!code && managers.length) setCode([...managers].sort((a, b) => a.name.localeCompare(b.name))[0].employeeCode); }, [managers, code]);
  return (
    <div className="space-y-5">
      <div className={CARD}>
        <TitleBar>Listeddr - Dump</TitleBar>
        <div className="flex flex-wrap items-end gap-4"><FieldForceSelect value={code} onChange={setCode} employees={managers} label="Filed Force Name" /></div>
        <div className="flex flex-col gap-1">
          <button type="button" className={DL_LINK} disabled={!code || !!dl.busy} onClick={() => void dl.run("csv", "/company/mis/listeddr-dump", { employeeCode: code, format: "csv" }, "Dump.csv")}>{dl.busy === "csv" ? "Preparing..." : "Download Excel"}</button>
          <button type="button" className="text-xs text-blue-700 underline text-left disabled:opacity-50" disabled={!code || !!dl.busy} onClick={() => void dl.run("xlsx", "/company/mis/listeddr-dump", { employeeCode: code, format: "xlsx" }, "Listeddr_Dump.xlsx")}>{dl.busy === "xlsx" ? "Preparing..." : "Download Excel (.xlsx)"}</button>
        </div>
        <Err msg={dl.error} />
        <Note>66 columns for every listed doctor of the manager&apos;s team. &quot;Download Excel&quot; gives Dump.csv in the legacy format (every field double-quoted, CRLF); the second link gives the same data as a real .xlsx.</Note>
      </div>
    </div>
  );
}
// ═══ 6. Dump > Chemist ════════════════════════════════════════════════════
export function ChemistDumpReport() {
  return <ManagerMonthDump title="Chemist - Dump" noMonth path="/company/mis/chemist-dump" fileName={() => "Chemist_Dump.xlsx"} note="Sheet Chemist: the chemists mapped to the manager's team (12 columns)." />;
}

// ═══ 7. Dump > Transit Bills ══════════════════════════════════════════════
export function TransitBillsDumpReport() {
  const my = useMonthYear();
  const dl = useDownload();
  return (
    <div className="space-y-5">
      <div className={CARD}>
        <TitleBar>Transit Bills - At Glance</TitleBar>
        <div className="flex flex-wrap items-end gap-4">
          <MonthSel label="From Month" value={my.m} onChange={my.setM} />
          <YearSel label="From Year" value={my.y} onChange={my.setY} />
        </div>
        <button type="button" className={DL_LINK} disabled={!!dl.busy} onClick={() => void dl.run("x", "/company/mis/transit-bills-dump", { month: my.key }, `Transit_Bills_${my.key}.xlsx`)}>{dl.busy ? "Preparing..." : "Download Excel"}</button>
        <Err msg={dl.error} />
        <Note>Bills are entered or imported under Masters &gt; Sales &gt; Transit Bills.</Note>
      </div>
    </div>
  );
}

// ═══ 8. Dump > Listed Stockist ════════════════════════════════════════════
export function StockistDumpReport() {
  const [division, setDivision] = useState(DIVISION_NAME);
  const dl = useDownload();
  return (
    <div className="space-y-5">
      <div className={CARD}>
        <TitleBar back>Stockist - Dump</TitleBar>
        <div className="flex flex-col gap-1 w-72">
          <span className={LABEL}>Division Name</span>
          <select className={SELECT} value={division} onChange={(e) => setDivision(e.target.value)}><option value="ALL">ALL</option><option value={DIVISION_NAME}>{DIVISION_NAME}</option></select>
        </div>
        <button type="button" className={DL_LINK} disabled={!!dl.busy} onClick={() => void dl.run("x", "/company/mis/stockist-dump", { division }, "Stockist_Dump.xlsx")}>{dl.busy ? "Preparing..." : "Download Excel"}</button>
        <Err msg={dl.error} />
      </div>
    </div>
  );
}

// ═══ 9. Options > Resigned User Status ════════════════════════════════════
type RangeState = { fm: number; fy: number; tm: number; ty: number };
function useRange() {
  const [r, set] = useState<RangeState>({ fm: NOW_M, fy: THIS_YEAR, tm: NOW_M, ty: THIS_YEAR });
  return { r, set, from: ym(r.fy, r.fm), to: ym(r.ty, r.tm) };
}
function RangeForm({ title, range, loading, onView, error }: { title: string; range: ReturnType<typeof useRange>; loading: boolean; onView: () => void; error: string }) {
  const { r, set } = range;
  return (
    <div className={CARD}>
      <TitleBar>{title}</TitleBar>
      <div className="flex flex-wrap items-end gap-4">
        <MonthSel label="From Month" value={r.fm} onChange={(fm) => set({ ...r, fm })} />
        <YearSel label="From Year" value={r.fy} onChange={(fy) => set({ ...r, fy })} />
        <MonthSel label="To Month" value={r.tm} onChange={(tm) => set({ ...r, tm })} />
        <YearSel label="To Year" value={r.ty} onChange={(ty) => set({ ...r, ty })} />
        <button type="button" className={BTN_BLUE} disabled={loading} onClick={onView}>{loading ? "Loading..." : "View"}</button>
      </div>
      <Err msg={error} />
    </div>
  );
}
const TH_TEAL = "border border-black px-2 py-1 text-xs font-bold text-center bg-teal-700 text-white";
const TD = "border border-black px-2 py-1 text-xs text-center";

export function ResignedUserStatusReport() {
  const range = useRange();
  const [data, setData] = useState<ResignedUsersResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [hq, setHq] = useState("All");
  const [sort, setSort] = useState<{ key: "name" | "designation" | "hq"; dir: 1 | -1 } | null>(null);
  async function view() {
    if (range.from > range.to) { setError("From must not be after To."); return; }
    setLoading(true); setError("");
    try { setData((await apiClient.resignedUsers({ fromMonth: range.from, toMonth: range.to })).data); setHq("All"); setSort(null); }
    catch (e) { setError(e instanceof Error ? e.message : "Unable to load report"); setData(null); }
    finally { setLoading(false); }
  }
  const hqs = useMemo(() => [...new Set((data?.rows ?? []).map((r) => r.hq))].sort(), [data]);
  const rows = useMemo(() => {
    let out = (data?.rows ?? []).filter((r) => hq === "All" || r.hq === hq);
    if (sort) out = [...out].sort((a, b) => a[sort.key].localeCompare(b[sort.key]) * sort.dir);
    return out;
  }, [data, hq, sort]);
  const label = (m: string) => `${MONTH_NAMES[Number(m.slice(5, 7)) - 1].slice(0, 3)} ${m.slice(0, 4)}`;
  const sortHead = (key: "name" | "designation" | "hq", text: string) => (
    <th className={TH_TEAL}><button type="button" className="underline font-bold" onClick={() => setSort((p) => (p?.key === key ? { key, dir: (p.dir * -1) as 1 | -1 } : { key, dir: 1 }))}>{text}</button></th>
  );
  const openLink = (path: string, q: Record<string, string>) => `${WORKSPACE}/${path}?${new URLSearchParams(q).toString()}`;
  const title = data ? `Resigned User for the Period of ${label(data.from)} To ${label(data.to)}` : "";
  return (
    <div className="space-y-5">
      <RangeForm title="Resigned User Status" range={range} loading={loading} onView={() => void view()} error={error} />
      {data && (
        <ReportModal title={title} fileName={`Resigned_Users_${data.from}_${data.to}`} onClose={() => setData(null)} textButtons>
          <h3 className="text-center text-lg font-bold underline" style={{ color: "#b0124d" }}>{title}</h3>
          <div className="flex items-center gap-2 text-sm"><span className="font-semibold">HQ Wise Filter</span>
            <select className={SELECT} value={hq} onChange={(e) => setHq(e.target.value)}><option value="All">All</option>{hqs.map((h) => <option key={h} value={h}>{h}</option>)}</select></div>
          <table className="w-full border-collapse">
            <thead><tr>
              <th className={TH_TEAL}>S.No</th><th className={TH_TEAL}>Employee Code</th>{sortHead("name", "FieldForce Name")}{sortHead("designation", "Designation")}{sortHead("hq", "HQ")}
              <th className={TH_TEAL}>DCR Start Date</th><th className={TH_TEAL}>DCR End Date</th><th className={TH_TEAL}>TP View</th><th className={TH_TEAL}>DCR View</th><th className={TH_TEAL}>Leave Status</th>
            </tr></thead>
            <tbody>
              {rows.map((r, i) => (
                <tr key={r.employeeCode}>
                  <td className={TD}>{i + 1}</td><td className={TD}>{r.employeeCode}</td><td className={TD}>{r.name}</td><td className={TD}>{r.designation}</td><td className={TD}>{r.hq}</td>
                  <td className={TD}>{r.dcrStart}</td><td className={TD}>{r.dcrEnd}</td>
                  <td className={TD}><a className={link} target="_blank" rel="noreferrer" href={openLink("activity-reports/tp/view", { employeeCode: r.employeeCode, month: r.viewMonth })}>Click Here</a></td>
                  <td className={TD}><a className={link} target="_blank" rel="noreferrer" href={openLink("activity-reports/dcr/view", { employeeCode: r.employeeCode, month: r.viewMonth })}>Click Here</a></td>
                  <td className={TD}><a className={link} target="_blank" rel="noreferrer" href={openLink("division-options/leave-status", { name: r.name, from: data.from, to: data.to })}>Click Here</a></td>
                </tr>
              ))}
              {rows.length === 0 && <tr><td className={TD} colSpan={10}>No resigned users in this period.</td></tr>}
            </tbody>
          </table>
        </ReportModal>
      )}
    </div>
  );
}

// ═══ 10. Options > Join/Left Details ══════════════════════════════════════
const TH_SLATE = "px-2 py-3 text-sm font-semibold text-center text-white";
const TD_ROW = "border border-slate-300 px-2 h-12 text-sm text-center bg-white";
export function JoinLeftDetailsReport() {
  const range = useRange();
  const [data, setData] = useState<JoinLeftResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  async function view() {
    if (range.from > range.to) { setError("From must not be after To."); return; }
    setLoading(true); setError("");
    try { setData((await apiClient.joinLeft({ fromMonth: range.from, toMonth: range.to })).data); }
    catch (e) { setError(e instanceof Error ? e.message : "Unable to load report"); setData(null); }
    finally { setLoading(false); }
  }
  const full = (m: string) => `${MONTH_NAMES[Number(m.slice(5, 7)) - 1]} ${m.slice(0, 4)}`;
  const span = data ? `${full(data.from)} to ${full(data.to)}` : "";
  const headStyle = { backgroundColor: "#2f5a6e" };
  const Head = ({ cols }: { cols: string[] }) => <thead><tr style={headStyle}>{cols.map((c) => <th key={c} className={TH_SLATE + (c === "Division" ? " text-base font-extrabold" : "")}>{c}</th>)}</tr></thead>;
  return (
    <div className="space-y-5">
      <RangeForm title="Join/Left Details" range={range} loading={loading} onView={() => void view()} error={error} />
      {data && (
        <ReportModal title={`Join / Left Details ${span}`} fileName={`Join_Left_${data.from}_${data.to}`} onClose={() => setData(null)} textButtons>
          <h3 className="font-bold underline text-black text-lg">New Join Details For {span}</h3>
          <table className="w-full border-collapse">
            <Head cols={["S.No", "Employee Code", "FieldForceName", "HQ", "Designation", "Date of Join", "DCR StartDate", "Created ID", "Division"]} />
            <tbody>
              {data.joined.map((r) => (
                <tr key={r.employeeCode}><td className={TD_ROW}>{r.sno}</td><td className={TD_ROW}>{r.employeeCode}</td><td className={TD_ROW}>{r.name}</td><td className={TD_ROW}>{r.hq}</td><td className={TD_ROW}>{r.designation}</td><td className={TD_ROW}>{r.doj}</td><td className={TD_ROW}>{r.dcrStart}</td><td className={TD_ROW}>{r.createdId}</td><td className={TD_ROW + " font-bold"}>{r.division}</td></tr>
              ))}
              {data.joined.length === 0 && <tr><td className={TD_ROW} colSpan={9}>No new joinees in this period.</td></tr>}
            </tbody>
          </table>
          <h3 className="font-bold underline text-black text-lg pt-4">Left Out Details For {span}</h3>
          <table className="w-full border-collapse">
            <Head cols={["S.No", "Employee Code", "FieldForceName", "HQ", "Designation", "Date of Left", "DCR Last Date", "Deactive Date", "Division"]} />
            <tbody>
              {data.left.map((r) => (
                <tr key={r.employeeCode}><td className={TD_ROW}>{r.sno}</td><td className={TD_ROW}>{r.employeeCode}</td><td className={TD_ROW}>{r.name}</td><td className={TD_ROW}>{r.hq}</td><td className={TD_ROW}>{r.designation}</td><td className={TD_ROW}>{r.dateOfLeft}</td><td className={TD_ROW}>{r.dcrLast}</td><td className={TD_ROW}>{r.deactiveDate}</td><td className={TD_ROW + " font-bold"}>{r.division}</td></tr>
              ))}
              {data.left.length === 0 && <tr><td className={TD_ROW} colSpan={9}>Nobody left in this period.</td></tr>}
            </tbody>
          </table>
        </ReportModal>
      )}
    </div>
  );
}

// ═══ 11. TP - Deviation For Baselevel (layout inferred) ═══════════════════
export function TpDeviationReport() {
  const [code, setCode] = useState("");
  const my = useMonthYear();
  const [data, setData] = useState<TpDeviationResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  async function view() {
    if (!code) { setError("Select a field force."); return; }
    setLoading(true); setError("");
    try { setData((await apiClient.tpDeviation({ employeeCode: code, month: my.key })).data); }
    catch (e) { setError(e instanceof Error ? e.message : "Unable to load report"); setData(null); }
    finally { setLoading(false); }
  }
  const title = data ? `TP - Deviation For Baselevel - ${data.employee.name} - ${data.employee.designation} - ${data.employee.hq} for ${MONTH_NAMES[Number(data.month.slice(5, 7)) - 1]} ${data.month.slice(0, 4)}` : "";
  return (
    <div className="space-y-5">
      <div className={CARD}>
        <TitleBar>TP - Deviation For Baselevel</TitleBar>
        <div className="flex flex-wrap items-end gap-4">
          <FieldForceSelect value={code} onChange={setCode} label="Fieldforce Name" clearLabel={SELECT_FF} extraOptions={ADMIN_OPT.map((o) => ({ ...o, label: "admin" }))} />
          <MonthSel label="Month" value={my.m} onChange={my.setM} />
          <YearSel label="Year" value={my.y} onChange={my.setY} />
          <button type="button" className={BTN_BLUE} disabled={loading} onClick={() => void view()}>{loading ? "Loading..." : "View"}</button>
        </div>
        <Err msg={error} />
        <Note>Each base-level employee under the selected force: planned territory (approved/submitted tour plan) against the territory actually worked (doctors called). Deviation is Y when they differ, when a planned day has no call, or when a call has no plan.</Note>
      </div>
      {data && (
        <ReportModal title={title} fileName={`TP_Deviation_${data.month}`} onClose={() => setData(null)} textButtons>
          <h3 className="text-center text-lg font-bold underline" style={{ color: "#6b21a8" }}>{title}</h3>
          <table className="w-full border-collapse">
            <thead><tr><th className={TH_TEAL}>S.No</th><th className={TH_TEAL}>Emp.Code</th><th className={TH_TEAL}>FieldForce Name</th><th className={TH_TEAL}>Designation</th><th className={TH_TEAL}>HQ</th><th className={TH_TEAL}>Days Planned</th><th className={TH_TEAL}>Deviation Days</th></tr></thead>
            <tbody>
              {data.rows.map((r) => <tr key={r.employeeCode}><td className={TD}>{r.sno}</td><td className={TD}>{r.employeeCode}</td><td className={TD}>{r.name}</td><td className={TD}>{r.designation}</td><td className={TD}>{r.hq}</td><td className={TD}>{r.planned}</td><td className={TD}>{r.deviations}</td></tr>)}
              {data.rows.length === 0 && <tr><td className={TD} colSpan={7}>No base-level employees under this force.</td></tr>}
            </tbody>
          </table>
          <table className="w-full border-collapse mt-4">
            <thead><tr><th className={TH_TEAL}>Emp.Code</th><th className={TH_TEAL}>FieldForce Name</th><th className={TH_TEAL}>Date</th><th className={TH_TEAL}>Planned Territory</th><th className={TH_TEAL}>Worked Territory</th><th className={TH_TEAL}>Deviation</th></tr></thead>
            <tbody>
              {data.rows.flatMap((r) => r.days.map((d) => (
                <tr key={`${r.employeeCode}-${d.date}`}><td className={TD}>{r.employeeCode}</td><td className={TD}>{r.name}</td><td className={TD}>{d.date}</td><td className={TD}>{d.planned || "-"}</td><td className={TD}>{d.worked || "-"}</td>
                  <td className={TD} style={{ background: d.deviation === "Y" ? "#fde2e2" : undefined, fontWeight: 600 }}>{d.deviation}</td></tr>
              )))}
            </tbody>
          </table>
        </ReportModal>
      )}
    </div>
  );
}
